# Flutter build automation usign github actions.

on:
  push:
    branch: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
    - uses: actions/upload-artifact@v1
      with:
        name: release-bundle
        path: build/app/outputs/bundle/release/app-release.aab